### ISSUE TITLE
Constrain not actually constraining

### ISSUE THREAD

**Issue by elrom** [jrodanapolis/WE_AV-ABR_GPC_NanoESP32#1]
I'm not sure if this is an actual bug, or just tinker cruft.

https://github.com/jrodanapolis/WE_AV-ABR_GPC_NanoESP32/blob/8d7c5c29809169159374acf220e3026319e18f31/WE_AV-ABR_GPC_NanoESP32#L1136

**Comment by jrodanapolis** [comment]
Good catch - not sure what this line is doing in there. Line removed... thanks!

**Comment by jrodanapolis** [comment]
Good catch - not sure what this line is doing in there. Line removed... thanks!
